### ISSUE TITLE
jar for 0.0.5 version for scala 2.13 is empty 

### ISSUE THREAD

**Issue by Morgaroth** [VirtusLab/scala-yaml#177]
please see jar file published for 2.13:0.0.5 is empty (weights 300B - only META-INF dir)

https://repo1.maven.org/maven2/org/virtuslab/scala-yaml_2.13/0.0.5/scala-yaml_2.13-0.0.5.jar

**Comment by gauravkumar37** [comment]
+ @kpodsiad 
confirmed, please fix

**Comment by armanbilge** [comment]
Thanks for the ping, fix in https://github.com/VirtusLab/scala-yaml/pull/178.
