### ISSUE TITLE
Maven Jar for 2.13 (0.0.5) seems to be empty

### ISSUE THREAD

**Issue by wir33658** [VirtusLab/scala-yaml#179]
Integrated from https://mvnrepository.com/artifact/org.virtuslab/scala-yaml_2.13/0.0.5 , but Jar is empty (only Manifest).

**Comment by kpodsiad** [comment]
This should be fixed in https://github.com/VirtusLab/scala-yaml/pull/178 by @armanbilge  and `0.0.6` was released few minutes ago by @lwronski

**Comment by lwronski** [comment]
I will close this issue, because it was fixed in #178 and released in `0.0.6`.
