### ISSUE TITLE
Use default arguments when field is not provided

### ISSUE THREAD

**Issue by scalway** [VirtusLab/scala-yaml#215]
`Upickle` and some other `json` libraries uses default arguments when field is not provided. It'll highly improve readability of `yaml` when you don't need to provide optional fields, and will give Devs much more flexibility.

```scala

//> using scala "3.2.2"
//> using dep "org.virtuslab::scala-yaml:0.0.6"

import org.virtuslab.yaml.*

case class Foo(id:String, name:String = "optional") derives YamlCodec

val example1 = 
	"id: 0112\n" + 
	"name: Tottally not fake name\n"
	
val example2 = 
	"id: 0113\n"

println(">" + example1.as[Foo]) //> Right(Foo(0112,Tottally not fake name))
println(">" + example2.as[Foo]) //> Left(ConstructError(Key name doesn't exist in parsed document)) 
// expected                     //> Right(Foo(0113,optional))
```

**Comment by Flowdalic** [comment]
I am looking for a similar feature, where defaults can be omitted from configuration files. However, I wonder if this should only be done if the type is `Option`. So instead of

```scala
case class Foo(id:String, name:String = "optional") derives YamlCodec
```

you have

```scala
case class Foo(id:String, name:Option[String] = None) derives YamlCodec
```

**Comment by Flowdalic** [comment]
Ha, after wondering why I see code related to the functionality I am looking for, I've discovered that this was only recently added: 9054aff983c5591881f585f4310dd5187c970615 and not yet released.
