### ISSUE TITLE
Scala3doc is published for the test module?

### ISSUE THREAD

**Issue by kubukoz** [VirtusLab/scala-yaml#228]
Hi! I found this repo and wanted to see the documentation. I was surprised to see this:

<img width="879" alt="image" src="https://github.com/VirtusLab/scala-yaml/assets/894884/50efcc5d-428f-4391-93ea-ba366c481cc4">

None of this looks like library types:

<img width="688" alt="image" src="https://github.com/VirtusLab/scala-yaml/assets/894884/3b04fa1f-bbe0-42f1-a524-6b7019322d61">

I suppose there might be some publishing mix-up.

Update: interestingly enough, there are some other pages being generated (example: https://virtuslab.github.io/scala-yaml/org/virtuslab/yaml/internal.html), but they're not visible via navigation.

**Comment by kubukoz** [comment]
Did a bisect, gh-pages broke after 1f6847506009c93548c92a8f8522362daf709365.

**Comment by kubukoz** [comment]
ok, actually a bisect isn't great here because this issue seems to have happened (and been fixed) before.

So I started going one-by-one from the current `gh-pages` HEAD, which is 04f1364f617c26d2f6fbc71a476a3d43b5e0f24c (bad), and d25003252a1227d5426e0a3da736dcbc14f9be81
was already a good one. This makes me think it might be non-deterministic...

**Comment by kubukoz** [comment]
Just dumping thoughts here at this point. Found some sort of issue in the build. To reproduce:

1. `rm -rf **/target` inside this project, just to clear anything from sbt
2. `sbt`
3. in sbt, `doc`
4. see this: https://gist.github.com/kubukoz/47c33c4764d0591fe29cf1214c7efd4d

You can also do this in a more minimal way, with `compile` - it's enough to see the error.

**Comment by lbialy** [comment]
true

**Comment by lbialy** [comment]
Seems fine now, could not replicate the problem on current main, I will leave this open for some time.

**Comment by kubukoz** [comment]
I do see https://virtuslab.github.io/scala-yaml/org/virtuslab/yaml/TestRunner.html still - just for the record
