### ISSUE TITLE
Parse triple dot in a string

### ISSUE THREAD

**Issue by OndrejSpanel** [VirtusLab/scala-yaml#313]
Following returns error:

```
import org.virtuslab.yaml.*

val yaml = """
P:
  e: S...
  c: N
"""

yaml.asNode
```

Error is:
> org.virtuslab.yaml.ScannerError: Obtained Not found expected key for value but expected got MappingValue
> c: N
>   ^

See https://scastie.scala-lang.org/OndrejSpanel/jfavH3u2Sq29Gs5nQHmXKQ/23

**Comment by lbialy** [comment]
Hi @OndrejSpanel, ellipsis is used as a document end marker in yaml. Arguably, it should not be parsed as document end marker in this position and this is probably a bug. This works with `e: "S..."` btw.
