### ISSUE TITLE
Less readable failure msg for key with empty value in `0.2.0`

### ISSUE THREAD

**Issue by mims-github** [VirtusLab/scala-yaml#329]
We updated from `0.0.8` to `0.2.0` and experienced a change in a parsing failure:

For yaml: 

```
workflows:
         - name:
```

Gave in `0.0.8`:
`Workflow name cannot be empty`

and with `0.2.0`:
`Could't construct java.lang.String from null (tag:yaml.org,2002:null)`

Where as the following still gives the user friendly `cannot be empty` message:
```
 workflows:
          - name: ""
```

Was this change intended?
Maybe related to  changes for https://github.com/VirtusLab/scala-yaml/issues/86?

**Comment by lbialy** [comment]
What's the target case class to which you deserialized to? Yeah, this error
message is the updated one, but the circumstances when it occurs did not
change afair.

**Comment by mims-github** [comment]
Thanks for your quick reply.

It seems I mixed the failure msg, as the ` Workflow name cannot be empty` came from our validation code.

We use the `YamlDecoder.forString`

But I think the change was that before the first example parsed successfully to an empty string for the workflow name, and then our own validation kicked in.
Where as with `0.2.0`, it does not parse anymore, so we get the scala-yaml failure msg.

I guess that change is intended?

**Comment by lbialy** [comment]
Yes, null nodes should not be parsed as empty strings. If this field is
optional for you, wrap it in an Option[String] and you will receive None
for when this field is missing or is !!null.

**Comment by mims-github** [comment]
Awesome, thanks for your patience and clarifications.
