### ISSUE TITLE
Preserve order?

### ISSUE THREAD

**Issue by OndrejSpanel** [VirtusLab/scala-yaml#331]
In the following code the properties are printed in different order:
```
import org.virtuslab.yaml.*

val yaml = """
P:
  a: 0
  b: 1
  c: 2
  d: 3
  e: 4
"""

val node = yaml.asNode.toOption.get

node.asYaml
```

While property order is not mandated by YAML (or JSON), it is a common extension to support it (e.g. https://github.com/circe/circe-yaml/pull/23/files). Would it be possible to implement preserving property order in scala-yaml?

**Comment by lbialy** [comment]
It would be possible to preserve order. We would need to use a TreeMap during parsing.

**Comment by OndrejSpanel** [comment]
I see the release as published on github, but I do not see corresponding artifacts on Maven Central:

https://mvnrepository.com/artifact/org.virtuslab/scala-yaml

![image](https://github.com/user-attachments/assets/6e08db52-143b-4b61-9363-b5813c44fac8)

![image](https://github.com/user-attachments/assets/d280d2b3-13f9-4118-a299-b05d12306d9d)

Where can I get artifacts for testing, other then building them on my own?

**Comment by tgodzik** [comment]
It takes some time to appear there, best to look in https://repo1.maven.org/maven2/org/virtuslab/scala-yaml_3/0.3.0/
